### ISSUE TITLE
Too many repetitions occurs in one-back block

### ISSUE THREAD

**Issue by psychelzh** [psychelzh/n-back-child#13]
In testing period, sometimes one number occurs 4 times. Is this a problem?

**Comment by Zhouyu0206** [comment]
One number occurring 4 times means that subjects need to response 'yes' 3 times. Maybe reducing the occurrence times to 3 where subjects need to response 'yes' twice continuously is ok and necessary. Because if there is not a situation where subjects response samely twice, then subjects will generate the prediction that two consecutive reactions must be different. We don't want that happen, right?

**Comment by psychelzh** [comment]
It is okay. I will make sure "target" does not repeat more than two times.

**Comment by psychelzh** [comment]
This seems trivial and not so influential.
